/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
// import { db } from "../db/firebase";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <section className="px-8 mx-12 flex justify-center mt-10">
                <section className="pt-8 px-2 max-w-3xl">
                    <div className="flex flex-wrap mx-4 ">
                        <div className="md:w-1/3 px-2 mb-8">
                            <img
                                className="rounded shadow-md"
                                src="https://source.unsplash.com/random/1280x720"
                                alt=""
                            />
                        </div>
                        <div className="md:w-1/3 px-2 mb-8">
                            <img
                                className="rounded shadow-md"
                                src="https://source.unsplash.com/random/1280x720"
                                alt=""
                            />
                        </div>
                        <div className="md:w-1/3 px-2 mb-8">
                            <img
                                className="rounded shadow-md"
                                src="https://source.unsplash.com/random/1280x720"
                                alt=""
                            />
                        </div>
                        <div className="md:w-1/3 px-2 mb-8">
                            <img
                                className="rounded shadow-md"
                                src="https://source.unsplash.com/random/1280x720"
                                alt=""
                            />
                        </div>
                        <div className="md:w-1/3 px-2 mb-8">
                            <img
                                className="rounded shadow-md"
                                src="https://source.unsplash.com/random/1280x720"
                                alt=""
                            />
                        </div>
                        <div className="md:w-1/3 px-2 mb-8">
                            <img
                                className="rounded shadow-md"
                                src="https://source.unsplash.com/random/1280x720"
                                alt=""
                            />
                        </div>
                        <div className="md:w-1/3 px-2 mb-8">
                            <img
                                className="rounded shadow-md"
                                src="https://source.unsplash.com/random/1280x720"
                                alt=""
                            />
                        </div>
                        <div className="md:w-1/3 px-2 mb-8">
                            <img
                                className="rounded shadow-md"
                                src="https://source.unsplash.com/random/1280x720"
                                alt=""
                            />
                        </div>
                        <div className="md:w-1/3 px-2 mb-8">
                            <img
                                className="rounded shadow-md"
                                src="https://source.unsplash.com/random/1280x720"
                                alt=""
                            />
                        </div>
                    </div>
                </section>
            </section>
            <section className="px-8 mx-12 flex justify-center items-center">
                <div className="mr-6">
                    <input
                        className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                        id="username"
                        type="text"
                        placeholder="Username"
                    />
                </div>
                <div className="flex items-center justify-between">
                    <button
                        className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
                        type="button"
                    >
                        submit
                    </button>
                </div>
            </section>
        </>
    );
}
